In [3]:
import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("Messy_Employee_dataset.csv")

In [18]:
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,2021-04-02,59767.65,bob.davis@example.com,1651623197,Average,True
1,EMP1001,Bob,Brown,30.0,Finance-Texas,Active,2020-07-10,65304.66,bob.brown@example.com,1898471390,Excellent,True
2,EMP1002,Alice,Jones,30.0,Admin-Nevada,Pending,2023-12-07,88145.90,alice.jones@example.com,5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,2021-11-27,69450.99,eva.davis@example.com,3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,2022-01-05,109324.61,frank.williams@example.com,1586734256,Poor,False

In [19]:
df.shape

(1020, 12)

In [20]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   datetime64[ns]
 7   Salary             1020 non-null   float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(7)
memory usage: 88.8+ KB

In [22]:
df.duplicated().sum()

np.int64(0)

In [23]:
df["Employee_ID"].duplicated().sum()

np.int64(0)

In [24]:
df["Department_Region"].unique()

array(['DevOps-California', 'Finance-Texas', 'Admin-Nevada',
       'Cloud Tech-Florida', 'Sales-Texas', 'DevOps-New York',
       'Cloud Tech-New York', 'HR-New York', 'Finance-California',
       'Sales-Florida', 'DevOps-Illinois', 'Cloud Tech-Nevada',
       'Admin-Illinois', 'Cloud Tech-Illinois', 'Sales-Illinois',
       'Finance-Nevada', 'Admin-Texas', 'Sales-New York',
       'Finance-Florida', 'Admin-California', 'HR-Texas', 'HR-California',
       'HR-Nevada', 'Cloud Tech-Texas', 'Sales-California', 'HR-Illinois',
       'Admin-New York', 'Admin-Florida', 'HR-Florida', 'Sales-Nevada',
       'Finance-New York', 'DevOps-Florida', 'DevOps-Texas',
       'Finance-Illinois', 'Cloud Tech-California', 'DevOps-Nevada'],
      dtype=object)

In [13]:
df["Status"].unique()

array(['Active', 'Pending', 'Inactive'], dtype=object)

In [14]:
df["Performance_Score"].unique()

array(['Average', 'Excellent', 'Good', 'Poor'], dtype=object)

In [15]:
df["Department_Region"].str.split("-", expand=True).head()

            0           1
0      DevOps  California
1     Finance       Texas
2       Admin      Nevada
3       Admin      Nevada
4  Cloud Tech     Florida

In [16]:
df['Phone'] = df['Phone'].abs()

In [17]:
print(df['Phone'].head())

0    1651623197
1    1898471390
2    5596363211
3    3476490784
4    1586734256
Name: Phone, dtype: int64

In [25]:
df['Department'] = df['Department_Region'].str.split('-').str[0]

In [26]:
df['Region'] = df['Department_Region'].str.split('-').str[1]

In [27]:
print(df[['Department_Region', 'Department', 'Region']].head())

    Department_Region  Department      Region
0   DevOps-California      DevOps  California
1       Finance-Texas     Finance       Texas
2        Admin-Nevada       Admin      Nevada
3        Admin-Nevada       Admin      Nevada
4  Cloud Tech-Florida  Cloud Tech     Florida

In [28]:
df = df.drop('Department_Region', axis=1)

In [29]:
print(df.columns)

Index(['Employee_ID', 'First_Name', 'Last_Name', 'Age', 'Status', 'Join_Date',
       'Salary', 'Email', 'Phone', 'Performance_Score', 'Remote_Work',
       'Department', 'Region'],
      dtype='object')

In [30]:
df['Join_Date'] = pd.to_datetime(df['Join_Date'])

In [31]:
print(df['Join_Date'].dtype)

datetime64[ns]

In [32]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [33]:
df['Salary'] = df['Salary'].fillna(df['Salary'].median())

In [8]:
df.isnull().sum()

Employee_ID          0
First_Name           0
Last_Name            0
Age                  0
Department_Region    0
Status               0
Join_Date            0
Salary               0
Email                0
Phone                0
Performance_Score    0
Remote_Work          0
dtype: int64

In [34]:
df.groupby('Department')['Salary'].mean()

Department
Admin         85202.644096
Cloud Tech    84944.434658
DevOps        86003.638624
Finance       82279.519353
HR            85475.379474
Sales         86873.948258
Name: Salary, dtype: float64

In [35]:
df.groupby('Performance_Score')['Salary'].mean()

Performance_Score
Average      84210.734794
Excellent    85057.943933
Good         86309.466481
Poor         85043.017963
Name: Salary, dtype: float64

In [36]:
df.to_csv('employees_cleaned.csv', index=False)
print("Exported successfully ✅")

Exported successfully ✅